### ISSUE TITLE
Update for Py3

### ISSUE THREAD

**Issue by LibertyType** [jenskutilek/WoLiBaFoNaGen#3]
Since G3 is now released will **WoLiBaFoNaGen** be updated to use Py3 also?

**Comment by jenskutilek** [comment]
This is a standalone script and not related to Glyphs, but of course an upgrade to Python 3 would be nice :)

**Comment by jenskutilek** [comment]
Python 3 and Glyphs version have been added around a212416bc7c414b2d143264a3118cbd60694d632.
