### ISSUE TITLE
Current version isn't the same

### ISSUE THREAD

**Issue by LibertyType** [jenskutilek/WoLiBaFoNaGen#4]
I just installed the plugin using Plugin Manager in Glyphs 3 and see that your image of the plugin has a "Generate" button but mine only allows me to Save Settings.

Is there a reason for this?

**Comment by LibertyType** [comment]
Never mind. I figured out that you had made some changes.

**Comment by jenskutilek** [comment]
The screenshot in GitHub is indeed from the standalone version, which is slightly different from the Glyphs plugin. In Glyphs, use _Edit > Suggest New Font Name_ to generate a name matching your previously set criteria.
