### ISSUE TITLE
Crash in Glyphs 3

### ISSUE THREAD

**Issue by weiweihuanghuang** [jenskutilek/WoLiBaFoNaGen#6]
I get this crash on opening GA 3.2 (3179)
```
A plugin caused a crash

The Plugin WoLiBaFoNaGen.glyphsPlugin has caused a crash. Please update it by opening the Plugin Manager or re-downloading it from the original source.

Details:
Traceback (most recent call last):

  File "GlyphsApp/GlyphsApp/plugins.py", line 860, in loadPlugin

  File "plugin.py", line 73, in start
    self.load_defaults()

  File "plugin.py", line 115, in load_defaults
    setattr(self.fng, k, saved or v)

  File "FontNameGenerator.py", line 77, in word_list
    self.load_wordlist()

  File "FontNameGenerator.py", line 160, in load_wordlist
    with codecs.open(str(file_path), "rb", "utf-8") as txt_file:

  File "codecs.py", line 905, in open
    file = builtins.open(filename, mode, buffering)

FileNotFoundError: [Errno 2] No such file or directory: '~/Library/Application Support/Glyphs 3/Repositories/WoLiBaFoNaGen/WoLiBaFoNaGen.glyphsPlugin/wordsEn.txt'

App:3.2-3180 Plugin:2.0.1-201 System:11.6.1
```

Seems like it can't find it's own folder correctly

**Comment by jenskutilek** [comment]
Interesting! What kind of Python are you using, from python.org or from the Glyphs Plugin Manager?

**Comment by weiweihuanghuang** [comment]
So in the Settings > Addons, I have `3.9.15 (Homebrew)`, but interestingly when I get the `sys.executable` inside Glyphs App's macro panel I get `/Applications/Glyphs 3.app/Contents/MacOS/Glyphs 3`

**Comment by jenskutilek** [comment]
The path to the text files is different when the script is run inside the Glyphs plugin vs. the standalone app. With your Python version, apparently the detection is wrong. Could you post the output of this script in Glyphs?

```
import sys
print(hasattr(sys, "frozen"))
```

**Comment by weiweihuanghuang** [comment]
I get `True`

**Comment by jenskutilek** [comment]
It may work better now with the [latest release](/jenskutilek/WoLiBaFoNaGen/releases/tag/v2.0.2), I've improved the code to find the word list folder.
